"""Stage the hernia (YouTube-sourced) frames that must ship with the annotations.

The HeiCo and LapChole frames are regenerated by the recipient from datasets they already
hold, so they are never redistributed. The hernia videos are different: they are not part of
FOCUS, and our agreement with the clinical collaborator permits sharing the **annotated
frames only** -- never the raw video, non-commercial research use only. So the frames the
questions refer to have to travel with the questions or the public release is unusable.

Two sets are staged:

  frames/clips/<video>/frame<NNNNNNN>.jpg   every frame referenced by a question in
                                            public/vqa/hernia_mesh.jsonl, named by its
                                            absolute index in the source video
  frames/annotated/<video>/<video>__HH-MM-SS.jpg
                                            the frames the annotators actually marked up,
                                            referenced by the `image` column of the CSVs

    python annotations/export_hernia_frames.py --frames-root <hernia_yt/frames> \
                                               --annot-frames <mesh_frames>
"""
import argparse, csv, json, shutil, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames-root", type=Path, required=True,
                    help="hernia_yt/frames -- one directory per video, frame<NNNNNNN>.jpg")
    ap.add_argument("--annot-frames", type=Path, required=True,
                    help="mesh_frames -- the frames shown to annotators")
    ap.add_argument("--train-file", type=Path, required=True,
                    help="the assembled training jsonl, for frames_indices")
    ap.add_argument("--out", type=Path, default=HERE / "public/frames")
    a = ap.parse_args()

    # 1. frames referenced by the questions
    need: dict[str, set[int]] = {}
    for line in a.train_file.open():
        r = json.loads(line)
        if r.get("source_dataset") != "hernia_yt":
            continue
        need.setdefault(Path(r["frame_dir"]).name, set()).update(r["frames_indices"])

    clips, n_clip, missing = a.out / "clips", 0, []
    for video, idx in sorted(need.items()):
        dst = clips / video
        dst.mkdir(parents=True, exist_ok=True)
        for i in sorted(idx):
            src = a.frames_root / video / f"frame{i:07d}.jpg"
            if not src.exists():
                missing.append(str(src)); continue
            shutil.copy2(src, dst / src.name); n_clip += 1

    # 2. frames the annotators marked up
    refs = set()
    for f in sorted((HERE / "public/raw/hernia_mesh_annotations").glob("*.csv")):
        for r in csv.DictReader(f.open()):
            refs.add((r["video"], r["image"]))
    ann, n_ann = a.out / "annotated", 0
    for video, image in sorted(refs):
        src = a.annot_frames / video / image
        if not src.exists():
            missing.append(str(src)); continue
        (ann / video).mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, ann / video / image); n_ann += 1

    size = sum(p.stat().st_size for p in a.out.rglob("*.jpg"))
    print(f"clips/     {n_clip} frames across {len(need)} videos")
    print(f"annotated/ {n_ann} frames")
    print(f"total      {size/1e6:.1f} MB -> {a.out}")
    if missing:
        print(f"MISSING {len(missing)}:", *missing[:5], sep="\n  ")
        sys.exit(1)


if __name__ == "__main__":
    main()
